from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Mapping, Optional, Sequence

import numpy as np

try:
    from ortools.constraint_solver import pywrapcp, routing_enums_pb2

    _HAS_ORTOOLS = True
except Exception:  # pragma: no cover - optional dependency
    _HAS_ORTOOLS = False

try:
    import networkx as nx
    from networkx.algorithms import approximation as nx_approx

    _HAS_NETWORKX = True
except Exception:  # pragma: no cover - optional dependency
    _HAS_NETWORKX = False

try:
    from python_tsp.heuristics import solve_tsp_simulated_annealing
    from python_tsp.exact import solve_tsp_dynamic_programming

    _HAS_PYTHON_TSP = True
except Exception:  # pragma: no cover - optional dependency
    _HAS_PYTHON_TSP = False


ROUTING_BACKENDS = ("ortools", "networkx", "python_tsp")
ROUTING_MODES = ("open_end_anywhere", "open_fixed_end", "closed")
ROUTING_METRICS = ("haversine", "euclidean", "travel_time")


@dataclass
class TSPRoute:
    """
    Ordered route generated by a TSP backend.
    """

    indices: np.ndarray
    points: np.ndarray
    total_cost: float
    backend: str
    mode: str
    metric: str


def haversine_distance_m(
    lat1: float,
    lon1: float,
    lat2: float,
    lon2: float,
) -> float:
    """Great-circle distance in meters."""
    r_earth = 6_371_000.0
    lat1_rad = np.deg2rad(lat1)
    lon1_rad = np.deg2rad(lon1)
    lat2_rad = np.deg2rad(lat2)
    lon2_rad = np.deg2rad(lon2)
    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad
    a = (
        np.sin(dlat / 2.0) ** 2
        + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(dlon / 2.0) ** 2
    )
    c = 2.0 * np.arctan2(np.sqrt(a), np.sqrt(max(1.0 - a, 0.0)))
    return float(r_earth * c)


def pairwise_distance_matrix(
    points: np.ndarray,
    *,
    metric: str = "haversine",
    speed_mps: float = 1.0,
    travel_time_matrix: Optional[np.ndarray] = None,
) -> np.ndarray:
    """
    Build pairwise distance or travel-time matrix for routing.
    """
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] != 2:
        raise ValueError("points must have shape (n, 2) with columns [lat, lon] or [x, y].")
    n = int(pts.shape[0])
    if n == 0:
        return np.zeros((0, 0), dtype=float)

    metric = str(metric).lower()
    if metric not in ROUTING_METRICS:
        raise ValueError(f"Unknown metric {metric!r}; expected one of {ROUTING_METRICS}.")

    if metric == "travel_time":
        if travel_time_matrix is not None:
            mat = np.asarray(travel_time_matrix, dtype=float)
            if mat.shape != (n, n):
                raise ValueError("travel_time_matrix shape must match (n_points, n_points).")
            return np.maximum(mat, 0.0)
        if speed_mps <= 0.0:
            raise ValueError("speed_mps must be > 0 for travel_time metric.")
        dist_m = pairwise_distance_matrix(pts, metric="haversine")
        return dist_m / float(speed_mps)

    out = np.zeros((n, n), dtype=float)
    if metric == "euclidean":
        diff = pts[:, None, :] - pts[None, :, :]
        out = np.linalg.norm(diff, axis=-1)
        np.fill_diagonal(out, 0.0)
        return out

    # Haversine metric.
    for i in range(n):
        for j in range(i + 1, n):
            d = haversine_distance_m(
                float(pts[i, 0]),
                float(pts[i, 1]),
                float(pts[j, 0]),
                float(pts[j, 1]),
            )
            out[i, j] = d
            out[j, i] = d
    return out


def solve_tsp_route(
    points: np.ndarray,
    *,
    start_index: int = 0,
    end_index: Optional[int] = None,
    backend: str = "ortools",
    mode: str = "open_end_anywhere",
    metric: str = "haversine",
    speed_mps: float = 1.0,
    travel_time_matrix: Optional[np.ndarray] = None,
    fallback_backends: Sequence[str] = ("networkx", "python_tsp"),
    ortools_time_limit_s: float = 3.0,
) -> TSPRoute:
    """
    Compute an ordered route through all points using an open/closed TSP formulation.

    Parameters
    ----------
    points:
        Array of shape (n, 2), interpreted as [lat, lon] for haversine metric or
        generic [x, y] for euclidean metric.
    start_index:
        Index of required start point.
    end_index:
        Required end index when mode is ``open_fixed_end``.
    backend:
        Requested backend: ``ortools`` (default), ``networkx``, or ``python_tsp``.
        If unavailable, the function tries fallbacks in order.
    mode:
        Route mode:
        - ``open_end_anywhere`` (default): start fixed, end unconstrained.
        - ``open_fixed_end``: start and end fixed.
        - ``closed``: tour returns to start.
    metric:
        ``haversine`` | ``euclidean`` | ``travel_time``.
    """
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] != 2:
        raise ValueError("points must have shape (n, 2).")
    n = int(pts.shape[0])
    if n == 0:
        raise ValueError("points must be non-empty.")
    if not (0 <= int(start_index) < n):
        raise ValueError("start_index out of range.")

    mode = str(mode).lower()
    if mode not in ROUTING_MODES:
        raise ValueError(f"Unknown mode {mode!r}; expected one of {ROUTING_MODES}.")

    if mode == "open_fixed_end":
        if end_index is None:
            raise ValueError("end_index is required for mode='open_fixed_end'.")
        if not (0 <= int(end_index) < n):
            raise ValueError("end_index out of range.")
    else:
        end_index = None

    dist = pairwise_distance_matrix(
        pts,
        metric=metric,
        speed_mps=speed_mps,
        travel_time_matrix=travel_time_matrix,
    )
    np.fill_diagonal(dist, 0.0)

    if n == 1:
        route_idx = np.array([0], dtype=int)
        if mode == "closed":
            route_idx = np.array([0, 0], dtype=int)
        return TSPRoute(
            indices=route_idx,
            points=pts[route_idx],
            total_cost=0.0,
            backend="trivial",
            mode=mode,
            metric=metric,
        )

    requested = str(backend).lower()
    backends = [requested]
    for b in fallback_backends:
        b = str(b).lower()
        if b not in backends:
            backends.append(b)

    last_error: Optional[Exception] = None
    for candidate in backends:
        try:
            if candidate == "ortools":
                route = _solve_with_ortools(
                    dist,
                    start_index=int(start_index),
                    end_index=end_index,
                    mode=mode,
                    time_limit_s=float(ortools_time_limit_s),
                )
            elif candidate == "networkx":
                route = _solve_with_networkx(
                    dist,
                    start_index=int(start_index),
                    end_index=end_index,
                    mode=mode,
                )
            elif candidate == "python_tsp":
                route = _solve_with_python_tsp(
                    dist,
                    start_index=int(start_index),
                    end_index=end_index,
                    mode=mode,
                )
            else:
                raise ValueError(f"Unknown backend {candidate!r}.")
            total = _route_cost(dist, route, mode=mode)
            route_idx = np.asarray(route, dtype=int)
            return TSPRoute(
                indices=route_idx,
                points=pts[route_idx],
                total_cost=float(total),
                backend=candidate,
                mode=mode,
                metric=metric,
            )
        except Exception as exc:  # pragma: no cover - backend fallback path
            last_error = exc
            continue

    # Deterministic pure-NumPy fallback.
    route = _solve_nearest_neighbor_fallback(
        dist,
        start_index=int(start_index),
        end_index=end_index,
        mode=mode,
    )
    total = _route_cost(dist, route, mode=mode)
    route_idx = np.asarray(route, dtype=int)
    backend_name = "nearest_neighbor_fallback"
    if last_error is not None:
        backend_name = f"{backend_name} ({type(last_error).__name__})"
    return TSPRoute(
        indices=route_idx,
        points=pts[route_idx],
        total_cost=float(total),
        backend=backend_name,
        mode=mode,
        metric=metric,
    )


def _route_cost(dist: np.ndarray, route: Sequence[int], *, mode: str) -> float:
    idx = list(int(i) for i in route)
    if len(idx) < 2:
        return 0.0
    total = 0.0
    for u, v in zip(idx[:-1], idx[1:]):
        total += float(dist[u, v])
    if mode == "closed" and idx[0] != idx[-1]:
        total += float(dist[idx[-1], idx[0]])
    return float(total)


def _normalize_cycle(cycle: Sequence[int], *, start_index: int) -> list[int]:
    seq = list(int(i) for i in cycle)
    if len(seq) < 2:
        return seq
    if seq[0] == seq[-1]:
        seq = seq[:-1]
    if start_index not in seq:
        raise ValueError("Cycle does not include requested start index.")
    k = seq.index(start_index)
    seq = seq[k:] + seq[:k]
    return seq


def _augment_for_open_mode(
    dist: np.ndarray,
    *,
    start_index: int,
    end_index: Optional[int],
    mode: str,
) -> tuple[np.ndarray, Optional[int]]:
    if mode == "closed":
        return np.asarray(dist, dtype=float), None

    n = int(dist.shape[0])
    dummy = n
    out = np.full((n + 1, n + 1), 0.0, dtype=float)
    out[:n, :n] = dist

    max_edge = float(np.max(dist))
    big_m = max(1.0, max_edge * (n + 2) + 1.0)
    out[dummy, :n] = big_m
    out[:n, dummy] = big_m
    out[dummy, dummy] = 0.0

    # Force one endpoint to be start.
    out[dummy, start_index] = 0.0
    out[start_index, dummy] = 0.0

    if mode == "open_fixed_end":
        if end_index is None:
            raise ValueError("end_index is required for open_fixed_end.")
        # Force the second endpoint to be end.
        out[dummy, end_index] = 0.0
        out[end_index, dummy] = 0.0

    return out, dummy


def _extract_open_route_from_augmented_cycle(
    cycle: Sequence[int],
    *,
    dummy_index: int,
    start_index: int,
    end_index: Optional[int],
    mode: str,
) -> list[int]:
    seq = list(int(i) for i in cycle)
    if seq and seq[0] == seq[-1]:
        seq = seq[:-1]
    if dummy_index not in seq:
        raise ValueError("Augmented cycle does not contain dummy node.")

    k = seq.index(dummy_index)
    forward = seq[k + 1 :] + seq[:k]
    backward = list(reversed(forward))

    candidates: list[list[int]] = []
    for cand in (forward, backward):
        cand = [x for x in cand if x != dummy_index]
        if not cand:
            continue
        if cand[0] != start_index:
            continue
        if mode == "open_fixed_end" and end_index is not None and cand[-1] != end_index:
            continue
        candidates.append(cand)

    if candidates:
        return candidates[0]

    # Fallback for degenerate approximate backend outputs.
    cleaned = [x for x in forward if x != dummy_index]
    if start_index in cleaned:
        k0 = cleaned.index(start_index)
        cleaned = cleaned[k0:] + cleaned[:k0]
    if mode == "open_fixed_end" and end_index is not None and cleaned[-1] != end_index:
        cleaned = [cleaned[0]] + list(reversed(cleaned[1:]))
    return cleaned


def _solve_with_ortools(
    dist: np.ndarray,
    *,
    start_index: int,
    end_index: Optional[int],
    mode: str,
    time_limit_s: float,
) -> list[int]:
    if not _HAS_ORTOOLS:
        raise ImportError("OR-Tools is not installed.")

    mat, dummy = _augment_for_open_mode(
        dist,
        start_index=start_index,
        end_index=end_index,
        mode=mode,
    )
    n = int(mat.shape[0])

    if mode == "closed":
        manager = pywrapcp.RoutingIndexManager(n, 1, int(start_index))
    elif mode in {"open_end_anywhere", "open_fixed_end"}:
        if dummy is None:
            raise RuntimeError("Expected dummy node for open mode.")
        manager = pywrapcp.RoutingIndexManager(
            n,
            1,
            [int(start_index)],
            [int(dummy)],
        )
    else:
        raise ValueError(f"Unknown mode: {mode!r}")

    routing = pywrapcp.RoutingModel(manager)
    scale = 1_000.0
    int_mat = np.rint(mat * scale).astype(np.int64)

    def transit_callback(from_index: int, to_index: int) -> int:
        u = manager.IndexToNode(from_index)
        v = manager.IndexToNode(to_index)
        return int(int_mat[u, v])

    transit_idx = routing.RegisterTransitCallback(transit_callback)
    routing.SetArcCostEvaluatorOfAllVehicles(transit_idx)

    params = pywrapcp.DefaultRoutingSearchParameters()
    params.first_solution_strategy = routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    params.local_search_metaheuristic = routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    params.time_limit.FromMilliseconds(max(1, int(round(float(time_limit_s) * 1_000.0))))

    solution = routing.SolveWithParameters(params)
    if solution is None:
        raise RuntimeError("OR-Tools failed to find a route.")

    route: list[int] = []
    index = routing.Start(0)
    while True:
        node = manager.IndexToNode(index)
        route.append(int(node))
        if routing.IsEnd(index):
            break
        index = solution.Value(routing.NextVar(index))

    if mode == "closed":
        route = _normalize_cycle(route, start_index=start_index)
        route.append(int(start_index))
        return route

    if dummy is None:
        raise RuntimeError("Expected dummy node for open mode.")
    return _extract_open_route_from_augmented_cycle(
        route,
        dummy_index=int(dummy),
        start_index=start_index,
        end_index=end_index,
        mode=mode,
    )


def _solve_with_networkx(
    dist: np.ndarray,
    *,
    start_index: int,
    end_index: Optional[int],
    mode: str,
) -> list[int]:
    if not _HAS_NETWORKX:
        raise ImportError("networkx is not installed.")

    mat, dummy = _augment_for_open_mode(
        dist,
        start_index=start_index,
        end_index=end_index,
        mode=mode,
    )
    n = int(mat.shape[0])
    G = nx.complete_graph(n)
    for i, j in G.edges():
        G[i][j]["weight"] = float(mat[i, j])

    cycle = nx_approx.traveling_salesman_problem(
        G,
        cycle=True,
        weight="weight",
        method=nx_approx.greedy_tsp,
    )
    seq = list(int(i) for i in cycle)

    if mode == "closed":
        seq = _normalize_cycle(seq, start_index=start_index)
        seq.append(int(start_index))
        return seq

    if dummy is None:
        raise RuntimeError("Expected dummy node for open mode.")
    return _extract_open_route_from_augmented_cycle(
        seq,
        dummy_index=int(dummy),
        start_index=start_index,
        end_index=end_index,
        mode=mode,
    )


def _solve_with_python_tsp(
    dist: np.ndarray,
    *,
    start_index: int,
    end_index: Optional[int],
    mode: str,
) -> list[int]:
    if not _HAS_PYTHON_TSP:
        raise ImportError("python_tsp is not installed.")

    mat, dummy = _augment_for_open_mode(
        dist,
        start_index=start_index,
        end_index=end_index,
        mode=mode,
    )
    n = int(mat.shape[0])
    if n <= 12:
        perm, _ = solve_tsp_dynamic_programming(mat)
    else:
        perm, _ = solve_tsp_simulated_annealing(mat)
    seq = [int(i) for i in perm] + [int(perm[0])]

    if mode == "closed":
        seq = _normalize_cycle(seq, start_index=start_index)
        seq.append(int(start_index))
        return seq

    if dummy is None:
        raise RuntimeError("Expected dummy node for open mode.")
    return _extract_open_route_from_augmented_cycle(
        seq,
        dummy_index=int(dummy),
        start_index=start_index,
        end_index=end_index,
        mode=mode,
    )


def _solve_nearest_neighbor_fallback(
    dist: np.ndarray,
    *,
    start_index: int,
    end_index: Optional[int],
    mode: str,
) -> list[int]:
    """
    Pure NumPy fallback route builder for environments without optional solvers.
    """
    n = int(dist.shape[0])
    unvisited = set(range(n))
    route = [int(start_index)]
    unvisited.remove(int(start_index))

    if mode == "open_fixed_end" and end_index is None:
        raise ValueError("end_index is required for open_fixed_end.")

    while unvisited:
        current = route[-1]
        # Keep the fixed end for the final position.
        if mode == "open_fixed_end" and end_index in unvisited and len(unvisited) == 1:
            nxt = int(end_index)
        else:
            choices = [u for u in unvisited if not (mode == "open_fixed_end" and u == end_index)]
            if not choices:
                choices = [int(end_index)] if end_index is not None else list(unvisited)
            costs = np.array([dist[current, u] for u in choices], dtype=float)
            nxt = int(choices[int(np.argmin(costs))])
        route.append(nxt)
        unvisited.remove(nxt)

    if mode == "closed":
        route.append(int(start_index))

    return route

